# Generated by Django 5.0.6 on 2024-09-09 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Appiontment',
            new_name='Appointment',
        ),
    ]
